version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5436:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/db-data
    environment:
      - POSTGRES_PASSWORD=Hiberus123
      - POSTGRES_USER=hiberusBank
      - POSTGRES_DB=postgresBank
volumes:
  db-data: