version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./docker:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Hiberus123
      - POSTGRES_USER=hiberusBank
      - POSTGRES_DB=postgresBank
volumes:
  db-data: